# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        # Indicamos que en User se utilizará un encoder con el algoritmo bcrypt con 4 veces encriptado
        BackendBundle\Entity\User:
            algorithm: bcrypt
            cost: 4    

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #Indicamos cual va a ser el provider de la autentificacion, es decir, que entidad nos va a proporcionar la autentificacion del usuario
        #donde el 'username' será en realidad el email
        user_db_provider:
            entity:
                class: BackendBundle:User
                property: email
                
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            # check_path es el path encargada de la comprobacion automatica del formulario
            # target indica a donde nos va a llevar cuando salga de la sesion.
            provider: user_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: logout
                target: /
    access_control:
        # En /login y en/register puede entrar los usuarios no autenticados, anonimos
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        # En la mayoria de las rutas solo pueden entrar los usuarios con ROLE_USER o ROLE_ADMIN
        - { path: ^/edit-user, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/profile, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/people, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/people, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/search, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/search, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/check-nick-exists, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/home, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^//publication_remove/, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/user, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/like, roles: [ROLE_USER, ROLE_ADMIN]}        
        - { path: ^/follow, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/unfollow, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/following, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/followed, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/like, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/unlike, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/likes, roles: [ROLE_USER, ROLE_ADMIN]}
