login:
    path: /login
    defaults: { _controller: AppBundle:User:login }
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    
register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

edit_user:
    path: /edit-user
    defaults: { _controller: AppBundle:User:editUser }
    
check_nick_exists:
    path: /check-nick-exists
    defaults: { _controller: AppBundle:User:checkNickExists }
    methods: [POST]