login:
    path: /login
    defaults: { _controller: AppBundle:User:login }
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    
register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

edit_user:
    path: /edit-user
    defaults: { _controller: AppBundle:User:editUser }

profile_user:
    path: /profile/{nickname}
    defaults: { _controller: AppBundle:User:profile, nickname:null }
    
check_nick_exists:
    path: /check-nick-exists
    defaults: { _controller: AppBundle:User:checkNickExists }
    methods: [POST]

user_list:
    path: /people
    defaults: { _controller: AppBundle:User:users }

user_search:
    path: /search
    defaults: { _controller: AppBundle:User:search }